### ISSUE TITLE
Suggestion: Change search filters to checkbox as opposed to radio

### ISSUE THREAD

**Issue by silvercheckmate** [Zicore/CrossoutMarket#66]
Currently the search filters behave like radio buttons, you can only select 1 faction or 1 rarity type. By switching to checkbox style filters, users can perform more types of searches. 

Use Cases:
User wants to search for all craftable epic gear to find profitable items to craft. Selecting epic rarity would also return decor items. At best the user can select epic weapons. then search for epic hardware, and so on and so forth.

**Comment by andrewpros** [comment]
@Stiffi136 

There was an update with this "It is now possible to apply multiple filters and they don't reload the page anymore "

But, can we have an option to use it like it was before?

Now if i want just to change type of component in all factions and the same rarity i need to double click, the old filter like cabins and the new, like weapons, cuz it adds now filters instead of toggling. 

Toggling was better for some things as there are too many item to track when more filters are enabled.

**Comment by andrewpros** [comment]
@Stiffi136 

There is another issue with this change, you cannot anymore refresh the prices just by F5 in browser.
